# Generated by Django 3.1.2 on 2020-11-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeeadvpred', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musician',
            new_name='rank',
        ),
    ]
